name: NodeJS with Grunt

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "feature/**" ]

jobs:
  runs-on: ubuntu-latest

  strategy:
    matrix:
      node-version: [ 18.x ]

  build-server:
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build Server
      run: |
        echo Building backend server...
        cd backend
        npm install

  build-app:
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build App
        run: |
          echo Building App...
          cd workout-app
          npm install
        
  
